apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: CRM
      port: 7021
      type: REST
      networkVisibility: Public
  outbound:
    serviceReferences:
    - name: choreo:///kanushkagayan/miri/qoegxk/08f62/v1.0/PUBLIC
      connectionConfig: 01eed070-2aea-1a78-b5d1-e02a0c6765ce
      env:
      - from: ServiceURL
        to: REC_URL
      - from: ConsumerKey
        to: CLIENT_ID
      - from: ConsumerSecret
        to: CLIENT_SECRET
      - from: TokenURL
        to: TOKEN_URL
